version: '2'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    image: tivixunicef/etools-proxy:dev
    ports:
      - "8080:80"
    depends_on:
      - backend
      #- pmp
      #- dashboard
      #- travel

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    image: tivixunicef/etools-db:dev

  backend:
    environment:
      DATABASE_URL: postgis://etoolusr:@db:5432/etools
      DJANGO_SETTINGS_MODULE: EquiTrack.settings.local
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: tivixunicef/etools-backend:dev
    command: bash -c "sleep 10 && /code/wait-for-it.sh db:5432 && python /code/EquiTrack/manage.py migrate_schemas && python /code/EquiTrack/manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./backend:/code
      - /data
    depends_on:
      - db
#
#  pmp:
#    build:
#      context: ./pmp
#      dockerfile: ./Dockerfile
#    image: tivixunicef/etools-pmp:dev
#    # volumes:
#    #   - "./pmp:/code"
#    command: [polymer, serve, -H, 0.0.0.0]  # doesn't have auto-reload yet https://github.com/Polymer/polymer-cli/issues/230
#
#  dashboard:
#    build:
#      context: ./pmp
#      dockerfile: ./Dockerfile
#    image: tivixunicef/etools-dashboard:dev
#    # volumes:
#    #   - "./dashboard:/code"
#    command: [polymer, serve, -H, 0.0.0.0]  # doesn't have auto-reload yet https://github.com/Polymer/polymer-cli/issues/230
#
#  travel:
#    build:
#      context: ./travel
#      dockerfile: ./Dockerfile
#    image: tivixunicef/etools-travel:dev
#    # volumes:
#    #   - "./travel:/code"
#    command: [polymer, serve, -H, 0.0.0.0]  # doesn't have auto-reload yet https://github.com/Polymer/polymer-cli/issues/230
