version: '2.1'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    image: etoolsdev/etools-proxy:dev
    ports:
      - "8082:80"
    depends_on:
      - backend
      - pmp
      - dashboard
      - travel
      - ap
    command: bash -c "./docker-entrypoint.sh && nginx -g 'daemon off;'${NX_CONFIG}"

  backend:
    environment:
      DEBUG_IP: ${DEBUG_IP:-"10.0.2.2"}
      DEBUG_PORT: ${DEBUG_PORT:-51312}
      DATABASE_URL: postgis://etoolusr:@db:5432/etools
      DJANGO_SETTINGS_MODULE: EquiTrack.settings.local
      PYCHARM_DEBUG: 1
    build:
      context: ./backend
      dockerfile: ./Dockerfile-dev
      args:
        REQUIREMENTS_FILE: local.txt
    image: etoolsdev/etools-backend:dev
    command: bash -c "sleep 10 && /code/wait-for-it.sh db:5432 && python /code/EquiTrack/manage${BACKEND_DEBUG}.py runserver 0.0.0.0:8080"
    volumes:
      - "./backend:/code"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    image: etoolsdev/etools-db:dev
#    volumes:
#      - './postgres_data:/var/lib/postgresql/data'

  pmp:
    build:
      context: ./pmp
      dockerfile: ./Dockerfile-dev
    image: etoolsdev/etools-pmp:dev
    volumes:
      - "./pmp:/code"
    command: ${FE_COMMAND:-sh -c "polymer serve -H 0.0.0.0 -p 8080"}
#
  dashboard:
    build:
      context: ./dashboard
      dockerfile: ./Dockerfile-dev
    image: etoolsdev/etools-dashboard:dev
    volumes:
      - "./dashboard:/code"
    command: ${FE_COMMAND:-sh -c "polymer serve -H 0.0.0.0 -p 8080"}
#
  travel:
    build:
      context: ./travel
      dockerfile: ./Dockerfile-dev
    image: etoolsdev/etools-travel:dev
    volumes:
      - "./travel:/code"
    command: ${FE_COMMAND:-sh -c "polymer serve -H 0.0.0.0 -p 8080"}

  ap:
    build:
      context: ./ap
      dockerfile: ./Dockerfile-dev
    image: etoolsdev/etools-ap:dev
    volumes:
      - "./ap:/code"
      - "/code/build"

